apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdcd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd
  template:
    metadata:
      labels:
        app: cicd
    spec:
      containers:
        - name: cicd
          image: wallpapers123/cdcd:latest
          ports:
            - containerPort: 8082


---

apiVersion: v1
kind: Service
metadata:
  name: my-nodeport-service
spec:
  selector:
    app: cicd
  type: NodePort
  ports:
    - port: 8082
      targetPort: 8082
      protocol: "TCP"